# aliases
alias sudo='sudo '
alias nf='neofetch'
alias pf='pfetch'
alias vim='nvim'
alias dot='yadm'
alias cat='bat'
alias ls='exa --icons --group-directories-first'
alias l='ls -l'
alias ll='ls -la'
