require("diegofigs.set")
require("diegofigs.nvim-treesitter")
require("diegofigs.telescope")
require("diegofigs.lspconfig")
require("diegofigs.lspsaga")
require("diegofigs.nvim-cmp")
require("diegofigs.nvim-tree")
require("diegofigs.lualine")
