#!/usr/bin/env bash

cd "$HOME" || return

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
    if ! command -v brew &> /dev/null;
    then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    brew bundle
fi

if [ "$system_type" = "Linux" ]; then
    if ! command -v yay &> /dev/null;
    then
        sudo pacman -S --needed git base-devel
        git clone https://aur.archlinux.org/yay-bin.git
        (cd yay-bin && makepkg -si --noconfirm)
        rm -rf yay-bin
    fi

    sudo pacman -S --needed --noconfirm - < ~/.config/pkglist.txt
    yay -S --needed --noconfirm --removemake --answerdiff=None - < ~/.config/aurlist.txt
    yay -Yc
fi

if command -v rtx &> /dev/null; then
    rtx install
fi

if ! command -v rustc &> /dev/null; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi

if ! command -v solana &> /dev/null; then
    sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
fi

if command -v cargo && ! command -v avm &> /dev/null; then
    cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
fi

if command -v avm &> /dev/null; then
    avm install latest
fi
