#!/usr/bin/env bash

cd $HOME

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ] && ! command -v brew &> /dev/null;
then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ "$system_type" = "Linux" ]; then
  if ! command -v yay &> /dev/null;
  then
    sudo pacman -S --needed git base-devel
    git clone https://aur.archlinux.org/yay-bin.git
    cd yay-bin
    makepkg -si --noconfirm
    cd ..
    rm -rf yay-bin
  fi

  make pacman-restore
  
  asdf plugin add nodejs
  asdf plugin add python
  asdf plugin add lua
  asdf install nodejs lts
  asdf install python 3.10.6
  asdf install python 2.7.18
  asdf install lua 5.1
fi
