name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck (zsh)
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_names: .zshrc .zlogin .zprofile prompt.zsh
          scandir: ".config/zsh"

  stylua:
    name: StyLua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.15.3
          args: --check .config/awesome .config/nvim/lua

  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: ".config/alacritty"
          yamllint_config_filepath: ".config/alacritty/.yamllint.yml"

