on:
  push:
    branches:
      - main

name: "CI"
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./.config/zsh"
          additional_files: ".config/polybar/scripts/*.sh .config/yadm/bootstrap"
  stylua:
    name: StyLua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.15.3
          args: --check .config/awesome .config/nvim/lua
