on:
  push:
    branches:
      - main

name: "CI"
jobs:
  shellcheck-zsh:
    name: Shellcheck - zsh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_names: .zshrc .zlogin .zprofile prompt.zsh
          scandir: ".config/zsh"
  shellcheck-yadm:
    name: Shellcheck - yadm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: ".config/yadm" 
  shellcheck-polybar:
    name: Shellcheck - polybar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: ".config/polybar/scripts"
  stylua:
    name: StyLua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.15.3
          args: --check .config/awesome .config/nvim/lua
