on:
  push:
    branches:
      - main

name: "CI"
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck (zsh)
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_names: .zshrc .zlogin .zprofile prompt.zsh
          scandir: ".config/zsh"
      - name: Run ShellCheck (yadm)
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: ".config/yadm"
      - name: Run ShellCheck (polybar)
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: ".config/polybar/scripts"
  stylua:
    name: StyLua
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.15.3
          args: --check .config/awesome .config/nvim/lua
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.config/alacritty'
          yamllint_strict: false
